In [2]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import torch


In [3]:
print("Printing the versions")
print(f"Torch version: {torch.__version__}")
print(f"Numpy version: {np.__version__}")
print(f"Matplotlib version: {matplotlib.__version__}")

Printing the versions
Torch version: 2.8.0+cpu
Numpy version: 2.3.3
Matplotlib version: 3.10.7


## Introduction to Tensors

### Creating Tensors

In [4]:
# Let's define a helper function to get the dimension and shape of the input tensor
def get_tensor_info(input_tensor):
    ndim = input_tensor.ndim
    shape = input_tensor.shape
    dtype = input_tensor.dtype
    print(f"The dim of the input tensor is : {ndim}")
    print(f"The shape of the input tensor is : {shape}")
    print(f"The data type of the input tensor is : {dtype}")

    if ndim == 0:
        print(f"The value of the input tensor is : {input_tensor.item()}")
    else:
        print(f"The value of the input tensor is : {input_tensor}")


In [5]:
# Scaler
scaler = torch.tensor(5)
get_tensor_info(scaler)

The dim of the input tensor is : 0
The shape of the input tensor is : torch.Size([])
The data type of the input tensor is : torch.int64
The value of the input tensor is : 5


In [6]:
# Let's create a vector
vector = torch.tensor([1, 2])
get_tensor_info(vector)


The dim of the input tensor is : 1
The shape of the input tensor is : torch.Size([2])
The data type of the input tensor is : torch.int64
The value of the input tensor is : tensor([1, 2])


Random Tensors are important in Neural Networks. Networks starts 
with random numbers -> look at the data -> update the numbes -> look at the 
data -> update the numbers -> iterate till the best numbers (parameters)
are found 

In [7]:
# Let's create a random tensor
random_tensor = torch.rand(4, 5)
get_tensor_info(random_tensor)

The dim of the input tensor is : 2
The shape of the input tensor is : torch.Size([4, 5])
The data type of the input tensor is : torch.float32
The value of the input tensor is : tensor([[0.9971, 0.0390, 0.5750, 0.7372, 0.0682],
        [0.2326, 0.1501, 0.9059, 0.1954, 0.7122],
        [0.3655, 0.3106, 0.3616, 0.2630, 0.0586],
        [0.4856, 0.7160, 0.0388, 0.7409, 0.2965]])


In [8]:
# Create a random tensor of the shape of an image tensor

image_tensor = torch.rand(size=(3, 224, 224))  # (Height, Width, Channel)
get_tensor_info(image_tensor)

The dim of the input tensor is : 3
The shape of the input tensor is : torch.Size([3, 224, 224])
The data type of the input tensor is : torch.float32
The value of the input tensor is : tensor([[[0.9864, 0.6943, 0.5651,  ..., 0.3010, 0.3252, 0.2509],
         [0.6074, 0.8936, 0.9679,  ..., 0.9097, 0.5079, 0.4653],
         [0.7532, 0.9942, 0.9313,  ..., 0.4570, 0.1738, 0.5913],
         ...,
         [0.0639, 0.2805, 0.7766,  ..., 0.8358, 0.9425, 0.7517],
         [0.0497, 0.0481, 0.4046,  ..., 0.0739, 0.2071, 0.8918],
         [0.6348, 0.3516, 0.5896,  ..., 0.5019, 0.7561, 0.0745]],

        [[0.1194, 0.7904, 0.2335,  ..., 0.3665, 0.0139, 0.1053],
         [0.7430, 0.3152, 0.7316,  ..., 0.9499, 0.2513, 0.9678],
         [0.6928, 0.0030, 0.6327,  ..., 0.5151, 0.3323, 0.2050],
         ...,
         [0.7738, 0.5327, 0.9042,  ..., 0.7325, 0.5708, 0.8652],
         [0.5357, 0.8276, 0.8703,  ..., 0.2463, 0.5173, 0.5756],
         [0.3603, 0.7174, 0.8687,  ..., 0.0323, 0.6535, 0.8899]],

    

In [9]:
# Zeros and Masks
zeros = torch.zeros(size=(4, 1))
get_tensor_info(zeros)

The dim of the input tensor is : 2
The shape of the input tensor is : torch.Size([4, 1])
The data type of the input tensor is : torch.float32
The value of the input tensor is : tensor([[0.],
        [0.],
        [0.],
        [0.]])


In [10]:
# Let's multiply it with the random tensor created above
random_tensor * zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [11]:
ones = torch.ones(4, 5)
get_tensor_info(ones)

The dim of the input tensor is : 2
The shape of the input tensor is : torch.Size([4, 5])
The data type of the input tensor is : torch.float32
The value of the input tensor is : tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [12]:
# Creating a range of tensors and tensors-like
range_tensor = torch.arange(start=1, end=11, step=1)
get_tensor_info(range_tensor)

The dim of the input tensor is : 1
The shape of the input tensor is : torch.Size([10])
The data type of the input tensor is : torch.int64
The value of the input tensor is : tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [13]:
# Tensors like
zeros_like = torch.zeros_like(range_tensor)
get_tensor_info(zeros_like)

The dim of the input tensor is : 1
The shape of the input tensor is : torch.Size([10])
The data type of the input tensor is : torch.int64
The value of the input tensor is : tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


In [14]:
ones_like = torch.ones_like(range_tensor)
get_tensor_info(ones_like)

The dim of the input tensor is : 1
The shape of the input tensor is : torch.Size([10])
The data type of the input tensor is : torch.int64
The value of the input tensor is : tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


### Tensor Datatypes

In [15]:
float_32_tensor = torch.tensor([3, 6, 9], dtype=None)
get_tensor_info(float_32_tensor)

The dim of the input tensor is : 1
The shape of the input tensor is : torch.Size([3])
The data type of the input tensor is : torch.int64
The value of the input tensor is : tensor([3, 6, 9])


## Common Pitfalls
**NOTE** Tensor datatypes is one of the 3 big errors to run into with PyTorch and DL
1. Tensors not having the right datatypes. Two tensors having different datatypes.
2. Tensors not having the right shape.
3. Tensors not having the same device. e.g. one on CPU and other on GPU.

In [16]:
float_16_tensor = torch.rand(size=(2, 4), dtype=torch.float16)
float_32_tensor = torch.rand(size=(2, 4), dtype=torch.float32)
get_tensor_info(float_16_tensor)
get_tensor_info(float_32_tensor)

The dim of the input tensor is : 2
The shape of the input tensor is : torch.Size([2, 4])
The data type of the input tensor is : torch.float16
The value of the input tensor is : tensor([[0.6421, 0.5229, 0.3774, 0.6313],
        [0.3828, 0.8579, 0.4185, 0.8164]], dtype=torch.float16)
The dim of the input tensor is : 2
The shape of the input tensor is : torch.Size([2, 4])
The data type of the input tensor is : torch.float32
The value of the input tensor is : tensor([[0.3718, 0.9573, 0.6695, 0.7052],
        [0.8647, 0.9839, 0.7986, 0.1328]])


In [17]:
# Let's try some mathematical operations on  two tensors of different dtypes
addition = float_16_tensor + float_32_tensor
get_tensor_info(addition)
subtraction = float_16_tensor - float_32_tensor
get_tensor_info(subtraction)
mutliplication = float_16_tensor * float_32_tensor
get_tensor_info(mutliplication)
division = float_16_tensor / float_32_tensor
get_tensor_info(division)

The dim of the input tensor is : 2
The shape of the input tensor is : torch.Size([2, 4])
The data type of the input tensor is : torch.float32
The value of the input tensor is : tensor([[1.0139, 1.4802, 1.0470, 1.3366],
        [1.2475, 1.8418, 1.2170, 0.9492]])
The dim of the input tensor is : 2
The shape of the input tensor is : torch.Size([2, 4])
The data type of the input tensor is : torch.float32
The value of the input tensor is : tensor([[ 0.2703, -0.4343, -0.2921, -0.0739],
        [-0.4819, -0.1260, -0.3801,  0.6836]])
The dim of the input tensor is : 2
The shape of the input tensor is : torch.Size([2, 4])
The data type of the input tensor is : torch.float32
The value of the input tensor is : tensor([[0.2388, 0.5006, 0.2527, 0.4453],
        [0.3310, 0.8441, 0.3342, 0.1084]])
The dim of the input tensor is : 2
The shape of the input tensor is : torch.Size([2, 4])
The data type of the input tensor is : torch.float32
The value of the input tensor is : tensor([[1.7268, 0.5463, 0.56

### Tensor Manipulation
* Addition
* Subtraction
* Multiplication (element-wise)
* Division 
* Matrix Multiplication

In [44]:
# Create an input tensor to manipulate
input_tensor = torch.tensor([10, 20, 30, 40, 50])
print(f"Input tensor: {input_tensor}")

# Addition
print(f"Result using python operator : {input_tensor + 10}")
print(f"Result using torch in-built function : {torch.add(input_tensor, 10)}")

Input tensor: tensor([10, 20, 30, 40, 50])
Result using python operator : tensor([20, 30, 40, 50, 60])
Result using torch in-built function : tensor([20, 30, 40, 50, 60])


In [29]:
# Subtraction
print(f"Result using python operator : {input_tensor - 10}")
print(f"Result using torch in-built function : {torch.sub(input_tensor, 10)}")

Result using python operator : tensor([ 0, 10, 20, 30, 40])
Result using torch in-built function : tensor([ 0, 10, 20, 30, 40])


In [28]:
# Multiplication (Element-wise)
print(f"Result using python operator : {input_tensor * 10}")
print(f"Result using torch in-built function : {torch.mul(input_tensor, 10)}")


Result using python operator : tensor([100, 200, 300, 400, 500])
Result using torch in-built function : tensor([100, 200, 300, 400, 500])


In [32]:
# Division
print(f"Result using python operator : {input_tensor / 10}")
print(f"Result using torch in-built function : {torch.div(input_tensor, 10)}")

Result using python operator : tensor([1., 2., 3., 4., 5.])
Result using torch in-built function : tensor([1., 2., 3., 4., 5.])


In [53]:
## Matrix Multplication
input_tensor = torch.rand(5, 5)
get_tensor_info(input_tensor)

The dim of the input tensor is : 2
The shape of the input tensor is : torch.Size([5, 5])
The data type of the input tensor is : torch.float32
The value of the input tensor is : tensor([[0.1146, 0.7661, 0.8024, 0.1342, 0.6981],
        [0.4378, 0.3243, 0.0308, 0.2651, 0.5201],
        [0.5354, 0.8750, 0.3555, 0.9444, 0.8484],
        [0.1980, 0.3511, 0.6887, 0.8730, 0.0660],
        [0.7700, 0.5649, 0.6426, 0.7409, 0.3615]])


In [54]:
# Element wise mutliplication
print("*******Element-Wise Mutiplication*****")
print(f"input_tensor * input_tensor : {input_tensor * input_tensor}")
print(f"Shape of the product : {(input_tensor * input_tensor).shape}")
print("*******Matrix Mutiplication*****")
print(
    f"input_tensor dot_product input_tensor : {torch.matmul(input_tensor, input_tensor)}"
)
print(f"Shape of the product : {torch.matmul(input_tensor, input_tensor).shape}")


*******Element-Wise Mutiplication*****
input_tensor * input_tensor : tensor([[0.0131, 0.5869, 0.6439, 0.0180, 0.4873],
        [0.1917, 0.1052, 0.0010, 0.0703, 0.2706],
        [0.2867, 0.7656, 0.1263, 0.8919, 0.7198],
        [0.0392, 0.1233, 0.4743, 0.7622, 0.0044],
        [0.5929, 0.3191, 0.4129, 0.5489, 0.1307]])
Shape of the product : torch.Size([5, 5])
*******Matrix Mutiplication*****
input_tensor dot_product input_tensor : tensor([[1.3423, 1.4799, 0.9418, 1.6107, 1.4205],
        [0.6617, 0.8545, 0.8891, 0.7907, 0.7060],
        [1.4750, 1.8158, 1.7785, 2.0926, 1.4995],
        [0.7688, 1.2120, 1.0582, 1.5811, 0.9866],
        [1.1047, 1.7997, 1.6063, 1.7746, 1.5561]])
Shape of the product : torch.Size([5, 5])


In [55]:
%%time
value = 0
print("Comparison of matrix multiplication with raw python vs torch.matmul")
for i in range(len(input_tensor)):
    value += input_tensor[i] * input_tensor[i]
print(value)


Comparison of matrix multiplication with raw python vs torch.matmul
tensor([1.1236, 1.9001, 1.6584, 2.2913, 1.6127])
CPU times: total: 15.6 ms
Wall time: 9.65 ms


In [56]:
%%time
value = torch.matmul(input_tensor, input_tensor)

CPU times: total: 0 ns
Wall time: 480 μs


In [60]:
print("Some common variants of PyTorch's matrix muliplication")
print(
    "\ttorch.matmul(T1,T2) : The standard one \n\t T1 @ T2 the shorthand \n\t torch.mm(T1,T2) the abbreviated one"
)

Some common variants of PyTorch's matrix muliplication
	torch.matmul(T1,T2) : The standard one 
	 T1 @ T2 the shorthand 
	 torch.mm(T1,T2) the abbreviated one


In [62]:
# Tensor Aggregation
# Create a tensor
x = torch.arange(0, 101, 10)
get_tensor_info(x)

The dim of the input tensor is : 1
The shape of the input tensor is : torch.Size([11])
The data type of the input tensor is : torch.int64
The value of the input tensor is : tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])


In [70]:
# Find the max
torch.max(x), x.max()

(tensor(100), tensor(100))

In [69]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [71]:
# Find the mean
# torch.mean() expects the dtype to be a floating point or complex dtype and not the current int type
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(50.), tensor(50.))

In [74]:
# Find the sum
torch.sum(x), x.sum()

(tensor(550), tensor(550))

In [76]:
# Geting the positional arguments for the max and min value in a tensor
print(f"The original tensor : {x}")
print(
    f"The max value is at the position : {torch.argmax(x)}"
)  # Remember the zero indexing, as the 100 is the 11th element
print(
    f"The min value is at the position : {torch.argmin(x)}"
)  # Remember the zero indexing


The original tensor : tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])
The max value is at the position : 10
The min value is at the position : 0


In [ ]:
# Helper function the get the position of the min and max value in the given tensor


from torch._tensor import Tensor


def get_argmin_and_argmax_value(
    given_tensor: torch.Tensor,
) -> tuple[Tensor, Tensor]:
    """Returns the position of the max and min value in the given tensor"""
    print(f"The given tensor : {given_tensor}")
    print(f"The max value is at position : {torch.argmax(given_tensor)}")
    max_value_position: torch.Tensor = torch.argmax(given_tensor)
    print(f"The min value is at position : {torch.argmin(given_tensor)}")
    min_value_position: torch.Tensor = torch.argmin(given_tensor)
    return max_value_position, min_value_position

In [81]:
max_pos, min_pos = get_argmin_and_argmax_value(x)
max_pos, min_pos

The given tensor : tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])
The max value is at position : 10
The min value is at position : 0


(tensor(10), tensor(0))

## Tensor Shape Manipulation
* Reshaping: Reshapes the input tensor to the desired shape.
* View:  Returns a view of the input tensor of a certain shape but keep the same memory as the original tensor.
* Stacking: Combine multiple tensors on top of each other either horizontally (hstack) or vertically (vstack).
* Squeeze: Remove all `1` dimensions from a tensor.
* Unsqueeze: Add a `1` dimension to a tensor.
* Permute: Reterns a view of the input with dimensions permuted (swapped) in a certain way.

In [92]:
# Let's create a tensor
x = torch.arange(1, 11)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [93]:
# Reshape
x_reshaped = x.reshape(10, 1)
x_reshaped, x_reshaped.shape

(tensor([[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10]]),
 torch.Size([10, 1]))

In [94]:
# View
# Remember that view shares the same memoery as the original
# Meaning: A change in 'z' would be reflected to x as well

z = x.view(2, 5)
z, z.shape

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 torch.Size([2, 5]))

In [95]:
z[1, 2] = 14
print(f"The updated value of z is : {z}")
print(f"The value of x also got updated  : {x}")

The updated value of z is : tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7, 14,  9, 10]])
The value of x also got updated  : tensor([ 1,  2,  3,  4,  5,  6,  7, 14,  9, 10])


In [96]:
# Stack tensors on top
x_horizontally_stacked = torch.stack([x, x, x, x], dim=0)
x_horizontally_stacked

tensor([[ 1,  2,  3,  4,  5,  6,  7, 14,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7, 14,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7, 14,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7, 14,  9, 10]])

In [99]:
x_vertically_stacked = torch.stack([x, x, x, x], dim=1)
x_vertically_stacked

tensor([[ 1,  1,  1,  1],
        [ 2,  2,  2,  2],
        [ 3,  3,  3,  3],
        [ 4,  4,  4,  4],
        [ 5,  5,  5,  5],
        [ 6,  6,  6,  6],
        [ 7,  7,  7,  7],
        [14, 14, 14, 14],
        [ 9,  9,  9,  9],
        [10, 10, 10, 10]])

In [100]:
# Squeeze - Removes all the `1` dimensions from the input tensor
x_reshaped, x_reshaped.shape


(tensor([[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [14],
         [ 9],
         [10]]),
 torch.Size([10, 1]))

In [107]:
a = torch.rand(2, 1, 3, 4, 1, 6)
# a,
a.shape

torch.Size([2, 1, 3, 4, 1, 6])

In [110]:
a_squeezed = a.squeeze()
# a_squeezed
a_squeezed.shape


torch.Size([2, 3, 4, 6])

The argument `dim` suppors a list of dimensions on which the `1` dimension would be squeezed.
NOTE: 
* If the dim passed is not zero, nothing happens.
* If no dim is passed, all the dimension with `1` would be removed (squeezed).
* If a valid argument for the squeeze is provided, then only that `1` dimension would be squeezed, other `1` dimensions would remain the same. 
* Squeeze operation shares the same memory as the original and therefore alters the original tensor as well, so beware of it.

In [112]:
# Let's unsqueeze
print(f"The shape of the squeezed tensor: {a_squeezed.shape}")

a_unsqueezed = a_squeezed.unsqueeze(dim=2)
print(f"The shape of the unsqueezed tensor : {a_unsqueezed.shape}")

The shape of the squeezed tensor: torch.Size([2, 3, 4, 6])
The shape of the unsqueezed tensor : torch.Size([2, 3, 1, 4, 6])


In [116]:
# Let's permute the tensor
b = torch.randn(size=(3, 6, 7, 4, 5, 2))
# b,
b.shape

torch.Size([3, 6, 7, 4, 5, 2])

In [118]:
b_permuted = b.permute(4, 2, 0, 5, 3, 1)
print(f"The shape of the tensor before permuation : {b.shape}")
print(f"The shape of the tensor after permuation : {b_permuted.shape}")

The shape of the tensor before permuation : torch.Size([3, 6, 7, 4, 5, 2])
The shape of the tensor after permuation : torch.Size([5, 7, 3, 2, 4, 6])


### Common Application of the permute function is in images, where (H,W,C) has to be permuted to (C,H,W)

In [ ]:
original_image_tensor: torch.Tensor = torch.rand(size=(224, 224, 3))
print(
    f"The shape of the original image tensor : {original_image_tensor.shape} (H x W x C)"
)
permuted_image_tensor: torch.Tensor = original_image_tensor.permute(dims=(2, 0, 1))
print(
    f"The shape of the permuted image tensor : {permuted_image_tensor.shape} (C x H x W)"
)

The shape of the original image tensor : torch.Size([224, 224, 3]) (H x W x C)
The shape of the permuted image tensor : torch.Size([3, 224, 224]) (C x H x W)


In [144]:
permuted_image_tensor[1][220][10] = 0.2525
permuted_image_tensor[1][220][10]

tensor(0.2525)

In [148]:
original_image_tensor[:, :, 1][220][10] = 0.349
original_image_tensor[:, :, 1][220][10]


tensor(0.3490)

In [149]:
original_image_tensor[:, :, 1][220][10]

tensor(0.3490)

In [150]:
permuted_image_tensor: torch.Tensor = original_image_tensor.permute(dims=(2, 0, 1))


In [151]:
permuted_image_tensor[1][220][10]

tensor(0.3490)

NOTE:
* As permute returns a view of the original tensor i.e. it shares the same memory location, a change in the permuted tensor results 
  a change in the original tensor as well. 

In [172]:
# Numpy to PyTorch and vice versa
np_array = np.arange(1.0, 10.0)
print(
    f"Numpy array has the following shape and dtype respectively : {np_array.shape}, {np_array.dtype}"
)
torch_array = torch.from_numpy(np_array)
print(
    f"The torch array converted from numpy has the following shape and dtype respectively : {torch_array.shape}, {torch_array.dtype}"
)
print("This means that torch takes the data type from the numpy array")


Numpy array has the following shape and dtype respectively : (9,), float64
The torch array converted from numpy has the following shape and dtype respectively : torch.Size([9]), torch.float64
This means that torch takes the data type from the numpy array


In [173]:
# To change this behavior
torch_array_float_32 = torch.from_numpy(np_array).type(torch.float32)
print(
    f"The explicitly created torch tensor now has the dtype : {torch_array_float_32.dtype}"
)

The explicitly created torch tensor now has the dtype : torch.float32


In [ ]:
# The creation of a tensor from a numpy array doesnot share the same memory. Change in the numpy array, doesnot change the created tensor form it
np_array = np_array + 2
np_array

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [175]:
torch_array

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [171]:
torch.__version__

'2.8.0+cpu'

In [176]:
## Reproducibility
tensor_a = torch.rand(4, 5)
tensor_b = torch.rand(4, 5)

# Lets compare the two
print(f"Tensor A: {tensor_a}")
print(f"Tensor B: {tensor_b}")
print(f"Are the two same ? \n {tensor_a == tensor_b}")


Tensor A: tensor([[0.8369, 0.2960, 0.8270, 0.2011, 0.3829],
        [0.2194, 0.1858, 0.5844, 0.3770, 0.1199],
        [0.3567, 0.6337, 0.8064, 0.7636, 0.0033],
        [0.3484, 0.6249, 0.6284, 0.3044, 0.8038]])
Tensor B: tensor([[0.2143, 0.9757, 0.6265, 0.3353, 0.4595],
        [0.9957, 0.1725, 0.4885, 0.2474, 0.6914],
        [0.1256, 0.1303, 0.5009, 0.0272, 0.6547],
        [0.3398, 0.3539, 0.7084, 0.8262, 0.8295]])
Are the two same ? 
 tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])


In [179]:
RANDOM_SEED = 88
torch.manual_seed(RANDOM_SEED)
tensor_c = torch.rand(4, 5)
tensor_d = torch.rand(4, 5)


# Lets compare the two
print(f"Tensor C: {tensor_c}")
print(f"Tensor D: {tensor_d}")
print(f"Are the two same ? \n {tensor_c == tensor_d}")

print(
    "Turns out the seed has to be set right before the operation for each such operation. Let's give it another shot, shall we?"
)

Tensor C: tensor([[0.7731, 0.6937, 0.8303, 0.4142, 0.2554],
        [0.0190, 0.4490, 0.8893, 0.1977, 0.2397],
        [0.8601, 0.3128, 0.6386, 0.9850, 0.0418],
        [0.9016, 0.8396, 0.3852, 0.9514, 0.9442]])
Tensor D: tensor([[0.7570, 0.9717, 0.5308, 0.2454, 0.0201],
        [0.8170, 0.6513, 0.8988, 0.3190, 0.6256],
        [0.4699, 0.1103, 0.6775, 0.0142, 0.3192],
        [0.9045, 0.8501, 0.6384, 0.1039, 0.3190]])
Are the two same ? 
 tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])
Turns out the seed has to be set right before the operation for each such operation. Let's give it another shot, shall we?


In [181]:
RANDOM_SEED = 88
torch.manual_seed(RANDOM_SEED)
tensor_c = torch.rand(4, 5)
torch.manual_seed(RANDOM_SEED)
tensor_d = torch.rand(4, 5)

# Lets compare the two
print(f"Tensor C: {tensor_c}")
print(f"Tensor D: {tensor_d}")
print(f"Are the two same ? \n {tensor_c == tensor_d}")

print(
    "Wolla! The two tensor created are the same now. \n This solves the concern of reproducibility."
)

Tensor C: tensor([[0.7731, 0.6937, 0.8303, 0.4142, 0.2554],
        [0.0190, 0.4490, 0.8893, 0.1977, 0.2397],
        [0.8601, 0.3128, 0.6386, 0.9850, 0.0418],
        [0.9016, 0.8396, 0.3852, 0.9514, 0.9442]])
Tensor D: tensor([[0.7731, 0.6937, 0.8303, 0.4142, 0.2554],
        [0.0190, 0.4490, 0.8893, 0.1977, 0.2397],
        [0.8601, 0.3128, 0.6386, 0.9850, 0.0418],
        [0.9016, 0.8396, 0.3852, 0.9514, 0.9442]])
Are the two same ? 
 tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])
Wolla! The two tensor created are the same now. 
 This solves the concern of reproducibility.


In [182]:
# Device agnostic code
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
DEVICE

'cpu'

In [183]:
# Putting tensors on the gpu, the default is cpu
tensor = torch.tensor([1, 2, 3])
tensor.device

device(type='cpu')

In [185]:
# Move tensor to gpu
tensor_to_gpu = tensor.to(DEVICE)
tensor_to_gpu.device

device(type='cpu')

In [186]:
# Tensors back to Numpy
# If the tensor is on the GPU, it cannot be converted to NumPy. Hence, first shift the tensor on cpu and then perform the conversion to numpy.

tensor_on_cpu = tensor_to_gpu.cpu()
tensor_back_to_numpy = tensor_on_cpu.numpy()