# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
import torch

torch.__version__

'2.11.0+cu128'

In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch


# Create random tensor
random_tensor = torch.rand(size=(7, 7))
random_tensor, random_tensor.shape

(tensor([[0.4763, 0.8980, 0.5623, 0.3016, 0.1281, 0.7035, 0.1145],
         [0.2470, 0.6682, 0.6947, 0.6257, 0.8742, 0.1688, 0.1004],
         [0.6191, 0.3607, 0.1307, 0.7548, 0.7059, 0.4737, 0.1131],
         [0.2898, 0.1079, 0.2329, 0.1807, 0.8210, 0.1529, 0.2317],
         [0.4956, 0.8092, 0.6032, 0.1782, 0.6163, 0.1207, 0.9223],
         [0.3194, 0.9203, 0.5993, 0.4170, 0.9077, 0.8565, 0.7384],
         [0.7712, 0.5026, 0.3708, 0.4059, 0.4279, 0.2257, 0.0467]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
second_random_tensor = torch.rand(size=(1, 7))
print(f"Second random tensor's shape before transpose: {second_random_tensor.shape}")
# Transpose the second random tensor inorder to perform matrix multiplication
second_random_tensor_transposed = second_random_tensor.T
print(f"Second random tensor's shape after transpose: {second_random_tensor.shape}")

# let's print the shape of the two tensors to be multiplied
print(f"Shape of the first tensor : {random_tensor.shape}")
print(f"Shape of the second tensor : {second_random_tensor.shape}")
print("Matrix mutiplication now possible")

# Perform matrix multiplication
product = torch.matmul(random_tensor, second_random_tensor_transposed)
print(f"Product of the two tensors : \n{product}")
print(f"Product of the two tensors has the shape : {product.shape}")

Second random tensor's shape before transpose: torch.Size([1, 7])
Second random tensor's shape after transpose: torch.Size([1, 7])
Shape of the first tensor : torch.Size([7, 7])
Shape of the second tensor : torch.Size([1, 7])
Matrix mutiplication now possible
Product of the two tensors : 
tensor([[1.3750],
        [1.1420],
        [0.8423],
        [0.5105],
        [1.6018],
        [1.6328],
        [1.0648]])
Product of the two tensors has the shape : torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors

torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(size=(7, 7))
tensor_B = torch.rand(size=(1, 7))
tensor_B_transposed = tensor_B.T
result = torch.matmul(tensor_A, tensor_B_transposed)
result, result.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [9]:
# Set random seed on the GPU
torch.cuda.manual_seed(seed=1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [16]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device : {device}")

first_random_tensor = torch.rand(2, 3).to(device)
second_random_tensor = torch.rand(2, 3).to(device)

# Create two random tensors on GPU
print(f"first_random_tensor : {first_random_tensor}")
print(f"second_random_tensor : {second_random_tensor}")

# # Set random seed
# torch.manual_seed(1234)

# # Check for access to GPU
# device = "cuda" if torch.cuda.is_available() else "cpu"
# print(f"Device: {device}")

# # Create two random tensors on GPU
# tensor_A = torch.rand(size=(2, 3)).to(device)
# tensor_B = torch.rand(size=(2, 3)).to(device)
# tensor_A, tensor_B


Device : cuda
first_random_tensor : tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
second_random_tensor : tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [18]:
# Perform matmul on tensor_A and tensor_B
product = torch.matmul(tensor_A, tensor_B.T)
product, product.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [21]:
# Find max
product.max()

# Find min
product.min()


tensor(0.3647, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [22]:
# Find arg max
argmin = torch.argmin(product)
print(argmin)

# Find arg min
argmax = torch.argmax(product)
print(argmax)

tensor(0, device='cuda:0')
tensor(3, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [25]:
# Set seed
torch.manual_seed(7)


# Create random tensor
random_tensor = torch.rand(1, 1, 1, 10)
print(random_tensor, random_tensor.shape)


# Remove single dimensions
random_tensor_squeezed = random_tensor.squeeze()

# Prinprint(f"Random tensor shape: {random_tensor.shape}")
print(f"random_tensor_squeezed: {random_tensor_squeezed}")
print(f"Random tensor shape after squeeze: {random_tensor_squeezed.shape}")


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
random_tensor_squeezed: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Random tensor shape after squeeze: torch.Size([10])
